export enum KeyService {
  // test
  TEST_QUERY = 'TEST_QUERY',
  TEST_MUTATION = 'TEST_MUTATION',
  TEST_PUSH_NOTIFICATION = 'TEST_PUSH_NOTIFICATION',
  TEST_UNAUTHORIZE = 'TEST_UNAUTHORIZE',

  // auth
  LOGIN = 'LOGIN',
  SIGN_UP = 'SIGN_UP',
  LOGOUT = 'LOGOUT',
  LOGIN_WITH_PHONE = 'LOGIN_WITH_PHONE',
  CONFIRM_OTP = 'CONFIRM_OTP',

  // restaurants
  GET_ALL_RESTAURANTS = 'GET_ALL_RESTAURANTS',

  // users
  SETUP_USER = 'SETUP_USER',
  GET_USER_SELF = 'GET_USER_SELF',
  CREATE_USER = 'CREATE_USER',

  // categories
  GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
  GET_ALL_CATEGORIES_WITH_ITEMS = 'GET_ALL_CATEGORIES_WITH_ITEMS',
  ADD_CATEGORY = 'ADD_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  EDIT_CATEGORY = 'EDIT_CATEGORY',
  GET_CATEGORY = 'GET_CATEGORY',

  // subCategories
  GET_ALL_SUB_CATEGORIES = 'GET_ALL_SUB_CATEGORIES',

  // items
  GET_ALL_ITEMS = 'GET_ALL_ITEMS',
  GET_ITEMS_BY_CATEGORY_ID = 'GET_ITEMS_BY_CATEGORY_ID',

  // carts
  ADD_CART = 'ADD_CART',
  GET_USER_CARTS_SELF = 'GET_USER_CARTS_SELF',

  // foods
  GET_ALL_FOODS = 'GET_ALL_FOODS',
}
