export enum EnteringAnimationEnum {
  UNDEFINED,

  FADE_IN,
  FADE_IN_RIGHT,
  FADE_IN_LEFT,
  FADE_IN_UP,
  FADE_IN_DOWN,

  BOUNCE_IN,
  BOUNCE_IN_RIGHT,
  BOUNCE_IN_LEFT,
  BOUNCE_IN_UP,
  BOUNCE_IN_DOWN,

  FLIP_IN_Y_RIGHT,
  FLIP_IN_Y_LEFT,
  FLIP_IN_X_UP,
  FLIP_IN_X_DOWN,
  FLIP_IN_EASY_X,
  FLIP_IN_EASY_Y,

  STRETCH_IN_X,
  STRETCH_IN_Y,

  ZOOM_IN,
  ZOOM_IN_ROTATE,
  ZOOM_IN_RIGHT,
  ZOOM_IN_LEFT,
  ZOOM_IN_UP,
  ZOOM_IN_DOWN,
  ZOOM_IN_EASY_UP,
  ZOOM_IN_EASY_DOWN,

  SLIDE_IN_RIGHT,
  SLIDE_IN_LEFT,
  SLIDE_IN_UP,
  SLIDE_IN_DOWN,

  LIGHT_SPEED_IN_RIGHT,
  LIGHT_SPEED_IN_LEFT,

  PINWHEEL_IN,

  ROLL_IN_LEFT,
  ROLL_IN_RIGHT,

  ROTATE_IN_DOWN_LEFT,
  ROTATE_IN_DOWN_RIGHT,
  ROTATE_IN_UP_LEFT,
  ROTATE_IN_UP_RIGHT,
}
export enum ExitingAnimationEnum {
  UNDEFINED,

  FADE_OUT,
  FADE_OUT_RIGHT,
  FADE_OUT_LEFT,
  FADE_OUT_UP,
  FADE_OUT_DOWN,

  BOUNCE_OUT,
  BOUNCE_OUT_RIGHT,
  BOUNCE_OUT_LEFT,
  BOUNCE_OUT_UP,
  BOUNCE_OUT_DOWN,

  FLIP_OUT_Y_RIGHT,
  FLIP_OUT_Y_LEFT,
  FLIP_OUT_X_UP,
  FLIP_OUT_X_DOWN,
  FLIP_OUT_EASY_X,
  FLIP_OUT_EASY_Y,

  STRETCH_OUT_X,
  STRETCH_OUT_Y,

  ZOOM_OUT,
  ZOOM_OUT_ROTATE,
  ZOOM_OUT_RIGHT,
  ZOOM_OUT_LEFT,
  ZOOM_OUT_UP,
  ZOOM_OUT_DOWN,
  ZOOM_OUT_EASY_UP,
  ZOOM_OUT_EASY_DOWN,

  SLIDE_OUT_RIGHT,
  SLIDE_OUT_LEFT,
  SLIDE_OUT_UP,
  SLIDE_OUT_DOWN,

  LIGHT_SPEED_OUT_RIGHT,
  LIGHT_SPEED_OUT_LEFT,

  PINWHEEL_OUT,

  ROLL_OUT_LEFT,
  ROLL_OUT_RIGHT,

  ROTATE_OUT_DOWN_LEFT,
  ROTATE_OUT_DOWN_RIGHT,
  ROTATE_OUT_UP_LEFT,
  ROTATE_OUT_UP_RIGHT,
}
